### ISSUE TITLE
Adding model weights to SeisBench

### ISSUE THREAD

**Issue by yetinam** [mktnaoi/JMAuniPicker#1]
Hi @mktnaoi ,
I've seen your very interesting manuscript on the PhaseNet and PhaseNetWC pickers your trained on the JMA catalog. Would you be okay, if I add your trained weights to the SeisBench repository? This way, they'd be available through the `from_pretrained` function. I'd clearly acknowledge your work in the docstring.

**Comment by mktnaoi** [comment]
Hi @yetinam,

Thank you for contacting me.

We would be very grateful if you would incorporate our JMA-retrained models into Seisbench software!
However, the paper in which the model is to be published is currently under review,
and there is the possibility that it will be modified during the review process.

It may be better to wait, at least, for the first peer review results to come back,
or to incorporate them after publication, to avoid confusion.

**Comment by yetinam** [comment]
Hi @mktnaoi ,
thanks for your quick reply! Then let's wait for the publication and we'll add the weights afterwards. Fingers crossed for the review process!

**Comment by mktnaoi** [comment]
Hi @yetinam,

The paper related to the model has been published.
(https://doi.org/10.1186/s40623-024-02091-8)
We are happy to incorporate the model into Seisbench!

**Comment by yetinam** [comment]
Hi @mktnaoi ,

first of all, congratulations to your new publication! I'd be happy to integrate your weights. On a related note, would you be interested in adding PhaseNetWC as well? I think it would be a great addition.

**Comment by mktnaoi** [comment]
Hi @yetinam,
> On a related note, would you be interested in adding PhaseNetWC as well? 
Including the PhaseNetWC model would be welcome!

**Comment by yetinam** [comment]
The `jma` weights are now available in SeisBench. Just use `sbm.PhaseNet.from_pretrained("jma")`. I added the PhaseNetWC version as well, but as it needs some code changes, it'll take until v0.9 to have it in the main release (https://github.com/seisbench/seisbench/pull/327). Thanks again for providing this! Maybe you could add a line to the README of this repository that the weights are now directly available in SeisBench?

**Comment by mktnaoi** [comment]
Hi @yetinam,

Thank you for your work.
I have updated the readme file!
